version: '3.4'

services:

  java:
    image: preet2fun/java:v2
    networks:
      - app-net


  prometheus:
    image: preetfun/prometheus:v2.3.1
    networks:
      - app-net

  grafana:
    image: psmonitoring/grafana:5.2.1
    networks:
      - app-net

networks:
  app-net: