global:
  scrape_interval: 10s
  external_labels:
    monitor: 'local-monitor'

scrape_configs:

  - job_name: 'java-app'
    metrics_path: /app-metrics/
    dns_sd_configs:
      - names:
        - tasks.java
        type: A
        port: 8080

#tasks.java reolve all ip address of containers which run under service tag java.
  - job_name: 'java-tomcat'
    metrics_path: /metrics/
    dns_sd_configs:
      - names:
        - tasks.java
        type: A
        port: 8080
# put swarm manager ip in target
  - job_name: 'docker-managers'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['10.211.55.16:50501']

# put swarm node ips in target

  - job_name: 'docker-workers'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['10.211.55.18:50501', '10.211.55.14:50501', '10.211.55.19:50501']